name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this REPO's with latest blogposts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@gustavo.diel"
