name: Latest github activities workflow
on:
  schedule:
    # Runs every hour
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-github-activity:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}